# BEGIN_KITTY_THEME
# Dracula
include current-theme.conf
# Configuración para ocultar bordes y título
#hide_window_decorations yes

# Sin relleno alrededor de la ventana
#window_padding_width 0

# Habilitar todos, configuración por default 
enabled_layouts *

# Deshabilitar la campana de la terminal
enable_audio_bell no

# Numero de lineas que mantiene la terminal
scrollback_lines 50000

# Tamaño maximo del historico de scrollback
scrollback_pager_history_size 50

# Multiplicador para el el numero de lineas desplazadas por la rueda del raton
wheel_scroll_multiplier 6

# Multiplicador para el el numero de lineas desplazadas por el panel tactil
touch_scroll_multiplier 15.0

# Incluiye la configuracion el fichero theme.conf
include ./theme.conf

# Configurar Opacidad
background_opacity 0.9

# Fuente
font_family      HackNerdFont

# Tamaño de fuente
font_size 11

# Asigna el valor a la variable $TERM (mantiene el tipo de terminal al conectarse a otros servidores)
term xterm-256color

# Desactiva el renderizado de ligaduras de multiples caracteres
disable_ligatures never

# Deteccion de URLs
detect_urls yes

# Color de las URLs
url_color #61afef

# Tipografia de las URLs
url_style curly

# Atajos para ir al numero de terminal indicado (del 1 al 9)
map ctrl+1 goto_tab 1
map ctrl+2 goto_tab 2
map ctrl+3 goto_tab 3
map ctrl+4 goto_tab 4
map ctrl+5 goto_tab 5
map ctrl+6 goto_tab 6
map ctrl+7 goto_tab 7
map ctrl+8 goto_tab 8
map ctrl+9 goto_tab 9

# Tipo de cursor
cursor_shape block

# Tiempo para que se oculte el raton
mouse_hide_wait 3.0

# Retraso en el dibujado
repaint_delay 10

map ctrl+up neighboring_window up
map ctrl+right neighboring_window right
map ctrl+down neighboring_window bottom
map ctrl+left neighboring_window left

# Atajos para redimensionar la ventana desde el teclado
map ctrl+shift+up resize_window top -10
map ctrl+shift+down resize_window bottom +10
map ctrl+shift+left resize_window left -10
map ctrl+shift+right resize_window right +10

# Retraso en ejecutar los entradas
input_delay 3

# Sincronizacion con el monitor para evitar el tearing
sync_to_monitor yes

# Plantilla para el titulo de la pestaña
tab_title_template "{index}: {title[title.rfind('/')+1:]}"

# Cambiar el nombre de la pestaña
map ctrl+n set_tab_title

# Estilo de la barra de pestañas
tab_bar_style powerline

# Colores para las pestañas segun su estado
inactive_tab_background #e06c75
active_tab_background #98c379
inactive_tab_foreground #000000

# Mapeo para salir de la terminal con 'Ctrl+Alt+Q'
map ctrl+alt+q close_window

# Mapeo para abrir una nueva ventana vertical pegada a la derecha con 'Ctrl+N'
map ctrl+n launch --location=vsplit --cwd=current

# Crear una nueva pestaña
map ctrl+shift+z new_tab_with_cwd 

# Cambiar el layout para poner el primer plano la ventana activa
map ctrl+0 goto_layout stack

# Ejecutar la shell de zsh
shell zsh

